### ISSUE TITLE
Fix ontology tags

### ISSUE THREAD

**Issue by mkutmon** [PathVisio/GPML#1]
Currently ontology tags are implemented as biopax elements but they are never references anywhere in the document and don't have an identifier. That means that they can't be read by the currrent API. I suggest to move the ontology tags from the biopax element and include them on a pathway level in a new XML tag. 

Currently there is a quick fix in PathVisio to read the ontology tags - for the RDF conversion - but they can't be changed and written out again. This is crucial to solve the mismatch problem between WP tags and the tags listed in the GPML.

**Comment by mkutmon** [comment]
New implementation (June 19 call): 
OntologyTerms - OntologyTerm → ontologyTermId / OntologyTermRef

**Comment by ariutta** [comment]
As in #3, I'm wondering whether it makes sense for `OntologyTermRef` to be a class when `graphRef` and `groupRef` are properties.

**Comment by mkutmon** [comment]
fixed in GPML2017
