### ISSUE TITLE
Multispecies pathways

### ISSUE THREAD

**Issue by mkutmon** [PathVisio/GPML#10]
**Reported by Egon** (http://developers.pathvisio.org/ticket/1758):
At the moment pathways are species specific, but with the increasing insight in the human biology, we learn that there are important multispecies processes, like the hot gut-brain axis. There is one pathway with multiple species:

 http://www.wikipathways.org/index.php/Pathway:WP2568

This was made by a guest at BiGCaT a while ago. Ideally, IMHO, the bacteria boxes get replaced by the actual process in those bacteria, and thus include the bacterial genes, etc.

Of course, there are many alternatives, but I think supporting this in GPML should not be too difficult.

At the moment the organism is specified at a pathway level, which can be left untouched. Following XML standards, this could be overwritten by child elements (i.e. DataNodes?) and we only need to introduce an optional @Organism attribute for DataNode?.

GPML Here we need to introduce a @Organism attribute for DataNode?. If given, then that DataNode? is from that species, overwriting the @Organism of the pathway. If the attribute is not given for the DataNode?, then it inherits the organism from the pathway.

PathVisio The DataNode? edit dialog needs extending with field to set the Organism. I would recommend a checkbox (unchecked by default) for "Overwrite Pathway Organism" (or something like that). If unchecked, the new field would be a disabled dropdown box with Organism values, set to the pathway organism. If checked, this dropdown would be enabled, still defaulting to the pathways species. (Alternatively, a text field is used, but I like the parallel with DataNode?@Type.) Only if the value of this field is different from the Pathway organism, the DataNode? @Organism attribute is used.

At a pathway enrichment level, the algorithm may need to take into account that genes should only be matches species specifically.

**Comment by mkutmon** [comment]
**Conversation:**
**Tina:** 
In GPML that is pretty straight forward. How would you solve it on WikiPathways??

**Egon:**
I could imagine the popup box would add an extra line of information if an @Organism tag is found. Optionally, though I think it would not be wrong keeping it as is, is to extend that pathway title with all organisms, instead of just the pathway one.

The linking out on WikiPathways? should be covered by BridgeDb. This currently works without species information, if not mistaken, and I do not think that needs to change. There are either mappings or not, and I think the BridgeDb web service has mappings for all (supported) species loaded anyway.

**Chris:**
I am not sure that is really needed. Not for this pathway in any case. This pathway is multi-species by nature but does not contain specific identifiers from any pathway. Also it actually is a meta-pathway that would link to species specific pathways were we to extend that. While I can think of processes where different organisms are involved these would most often consist of such species specific subpathways. What you proposed sounds like a lot of work for me for a problem that nobody might really have. Or do you have some examples in mind. If we are going into detailing identifiers I would in any case much rather solve that through a state kind of solution that would not only allow to change the species but also things like location, phosphorylation, activation level in general, histone acetylation, CpG island methylation and such.

**Comment by egonw** [comment]
Somewhat related: https://groups.google.com/forum/#!forum/combine-multicell

(Think microbiome bacterial cell <> human cell...)

**Comment by Finterly** [comment]
Organism  information will be introduced in DataNode(s) and other pathway elements using AnnotationRef/Annotation element in GPML2021 schema.
