### ISSUE TITLE
Make graphIds required

### ISSUE THREAD

**Issue by mkutmon** [PathVisio/GPML#11]
**Reported by Martijn** (http://developers.pathvisio.org/ticket/1431):
Update GPML so that graphIds are required. Currently they are optional. However, for validators and converters, it's very useful to be able to rely on them to be always there.

**Comment by mkutmon** [comment]
Not sure if this was already fixed for all elements - need to check!

**Comment by ariutta** [comment]
I know we did address this once, but I'm not sure it's part of the spec or in PathVisio.

**Comment by mkutmon** [comment]
@ariutta do you think all elements should have the required graphId? Also the Point class? Do we actually every refer to a Point object with a GraphRef?

**Comment by ariutta** [comment]
Consider this partial GPML example (made with PathVisio-Java):

```xml
  <Interaction GraphId="id7d368dc7">
    <Graphics ZOrder="12288" LineThickness="1.0">
      <Point X="572.0884872365941" Y="277.6867397635772" />
      <Point X="519.5590266875981" Y="468.8335949764521" GraphRef="e99f7" RelX="0.0" RelY="0.0" ArrowHead="mim-inhibition" />
    </Graphics>
    <Xref Database="" ID="" />
  </Interaction>
  <Interaction GraphId="ida94a52c5">
    <Graphics ZOrder="12288" LineThickness="1.0">
      <Point X="425.43171114599687" Y="396.3893249607535" />
      <Point X="660.75" Y="577.5" ArrowHead="mim-gap" />
      <Anchor Position="0.4" Shape="None" GraphId="e99f7" />
    </Graphics>
    <Xref Database="" ID="" />
  </Interaction>
```

Currently, a `Point` can have a `GraphRef` but not a `GraphId`. To reference a location on an edge, we currently reference an `Anchor`, which can have a `GraphId`.

If we don't make any fundamental changes to the `Interaction`/`GraphicalLine` classes, I don't see a need for `GraphId` to be added to `Point`. Can you think of any reason to add `GraphId` to `Point`, @egonw?

@AlexanderPico, we discussed an idea some time ago about making a change to the `Interaction` class. ~~I think it involved hyperedges and may have been related to AX + BY -> AY + BX, but I can't find the notes.~~ [See issue #14.] Do you remember that discussion? Did the change involve referencing a specific `Point` such that we would need to add `GraphId` to `Point`?

**Comment by egonw** [comment]
How are lines (interactions) connected then? Does that always require an anchor?

**Comment by ariutta** [comment]
Currently, yes. But if we implement the idea from issue #14, that could change.

**Comment by mkutmon** [comment]
See xsd - Point can already have a graphId. It's optional at the moment and I don't see any way this is used in the GUI. The question I had now was if this one should be required as well. 
```
<xsd:element name="Point" minOccurs="2" maxOccurs="unbounded">
	                                		<xsd:complexType>
	                                                <xsd:attribute name="X" type="xsd:float" use="required" />
	                                                <xsd:attribute name="Y" type="xsd:float" use="required" />
	                                                <!-- relX and relY are the coordinates used when
	                                                a point is linked to another object (when GraphRef
	                                                is defined). They represent he coordinates of the
	                                                point relative to the object that it's linked to, where
	                                                0,0 lies at the center of the object and 1,1 at the bottom-right
	                                                corner -->
	                                                <xsd:attribute name="RelX" type="xsd:float" use="optional" />
	                                                <xsd:attribute name="RelY" type="xsd:float" use="optional" />
	                                                <xsd:attribute name="GraphRef" type="xsd:IDREF" use="optional" />
	                                                <xsd:attribute name="GraphId" type="xsd:ID" use="optional" />
	                                                <!-- Note: only the ArrowHead attribute on first and last points are used, the rest is ignored. !-->
	                                                <xsd:attribute name="ArrowHead" default="Line" type="xsd:string" />
	                                                </xsd:complexType>
	                                          </xsd:element>
```

**Comment by ariutta** [comment]
If we don't implement #14 right now, I'm not sure it matters either way. We don't have GraphIds for elements like `Graphics` or `Xref` either.

For all elements, if GraphId is used as an attribute, it should always be required:
```
<xsd:attribute name="GraphId" type="xsd:ID" use="required" />
```

**Comment by Finterly** [comment]
GPML 2021 Schema, all elements including Points has required elementId (previously named graphId).
