### ISSUE TITLE
New DataNode type: Alias

### ISSUE THREAD

**Issue by AlexanderPico** [PathVisio/GPML#16]
A sibling of 'GeneProduct', 'Protein', 'Pathway' and others, this node type needs a new attribute, **GroupAliasRef**, in order to be connected to groups and complexes, but *not* as a member, i.e., located separately from the group.  

Ideally, we could also add **MemberXref**, which would be used by both 'Alias' and 'Pathway' DataNode types to optionally specify an aliased group/pathway member as the *connector node*, i.e., the node in the pathway or aliased group that actually participates in the interactions associated with the DataNode. 

If we really want to plan for the future, perhaps we could specify **SourceMemberXref** and **TargetMemberXref**, which would be particularly useful for 'Pathway' nodes and receptor complex 'Alias' nodes and reaction 'Alias' nodes, etc.

**Comment by mkutmon** [comment]
adding Alias graphical element which can link to any type of group (style: hexagon)

**Comment by Finterly** [comment]
DataNode, Interaction, GraphicalLine, Label, Shape, and Group elements can belong to a group and have groupRef. 
DataNode will have elementRef in addition to groupRef when a DataNode has type="Alias" and refers to a Group. 

Example for Group with Alias: 
`<DataNode elementId="c27d1" elementRef="d4107" textLabel="Alias_for_abc" .../>`
`<DataNode elementId="ed3f8" groupRef="d4107" textLabel="DataNode" type="GeneProduct" .../ >`
`<Label elementId="e180c" groupRef="d4107" textLabel="group_abc" .../>`
`<Group elementId="d4107" style="Complex".../>`

Example for nested Group with Aliases: 
`<DataNode elementId="a1" elementRef="efg" textLabel="Alias_for_efg" />`
`<DataNode elementId="a2" elementRef="abc" groupRef="efg" textLabel="Alias_for_abc" />`
`<DataNode elementId="a3" elementRef="abc" textLabel="Alias_for_abc" />`

`<DataNode elementId="n1" groupRef="abc" textLabel="DataNode;" type="GeneProduct" .../>`
`<DataNode elementId="n2" groupRef="efg" textLabel="DataNode;" type="GeneProduct" .../>`
`<Label elementId="n3" groupRef="abc" textLabel="group_abc" .../>`
`<Label elementId="n4" groupRef="efg" textLabel="group_efg".../>`

`<Group elementId="abc" Style="Complex" textLabel="GroupABC" groupRef="efg" />`
`<Group elementId="efg" Style="Complex" textLabel="GroupEFG" />`

commit 67de54a closes #16.
