### ISSUE TITLE
Group Element changes

### ISSUE THREAD

**Issue by AlexanderPico** [PathVisio/GPML#17]
1. Should "Style" attribute be renamed to "Type"?
2. New element types:
 - Complex (physically interacting sets of molecules that function as a coherent entity)
 - Paralogs (entities that share common sequence and function, often from a gene duplication event)
 - Analogs (entities that might not share an evolutionary link, but are functionally interchangeable in a given context) 
 - Reaction (mechanistic or biochemical details)
 - Graphical (just as a convenience for authoring; no biological meaning)

**Comment by mkutmon** [comment]
1. all Style attributes (except graphical - e.g. LineStyle) renamed to Type
2. New group types defined and added as enum in XSD - after libGPML is included in PV we'll need to update the UI `Group` (default), `Complex`, `Pathway`, `Analog`, `Paralog`
