### ISSUE TITLE
Should boardWidth / boardHeight be required?

### ISSUE THREAD

**Issue by ariutta** [PathVisio/GPML#18]
I was wondering why boardWidth / boardHeight for the Pathway element for GPML2017 is optional:

https://github.com/PathVisio/GPML/blob/df4209fa5f7d07e2a9ec0d245cb3a665b832b5fe/GPML2017.xsd#L261

Should it be required? That would be useful for rendering, because we would know the size of board even before we calculate where all the elements are located. I don't know how PathVisio handles this. @mkutmon

**Comment by ariutta** [comment]
Another question: would it make sense to simplify and just use `width`/`height` for the Pathway element, just like we do for other elements like DataNode and Label?

**Comment by mkutmon** [comment]
boardWidth and boardHeight were required in 2013a and should stay required in 2017. @saurabhkumar13  can you please update the schema?
I am find with simplifying to width/height.

**Comment by saurabhkumar13** [comment]
renamed to width/height and changed use to required
