### ISSUE TITLE
Pathway Version

### ISSUE THREAD

**Issue by ariutta** [PathVisio/GPML#19]
Right now, we have a [`version` property](https://github.com/PathVisio/GPML/blob/df4209fa5f7d07e2a9ec0d245cb3a665b832b5fe/GPML2017.xsd#L244) for `Pathway`, but that's confusing, because it's *not* the WikiPathways version. Rather, it appears to be the dataSource version, e.g., `dataSource="Reactome" version="58"` . Should this property be either removed or else renamed `dataSourceVersion`?

**Comment by saurabhkumar13** [comment]
I think this problem is addressed in the updated version at [libGPML repo](https://github.com/PathVisio/libGPML/blob/5477af0e40f77b975db56bb63a2705b8b3f468f9/resources/GPML2017.xsd), @mkutmon renamed `version` to `revision`
https://github.com/PathVisio/libGPML/commit/5477af0e40f77b975db56bb63a2705b8b3f468f9

**Comment by ariutta** [comment]
Here's the `Pathway` element for [WP1775](http://www.wikipathways.org/index.php/Pathway:WP1775):
```xml
<Pathway xmlns="http://pathvisio.org/GPML/2013a" Name="Cell Cycle Checkpoints" Data-Source="Reactome - http://www.reactome.org" Version="56" Author="Hoffmann, I, Khanna, KK, Walworth, N, Yen, Tim, O'Donnell, M" Maintainer="Matthews, Lisa" Email="lisa.matthews@cshl.edu" Organism="Homo sapiens">
...
</Pathway>
```

In this case, we have a Reactome version of `56` and a WikiPathways revision of `86525`. What should `version` and/or `revision` be? Anwesha's work says it should be `56`, because `Data-Source` and `Version` describe the same thing. The [GPML Vocabulary](https://vocabularies.wikipathways.org/gpml#version) is unclear.

**Comment by mkutmon** [comment]
Reactome pathways will not use these attributes in the future. Ryan already
fixed it.

**Comment by Finterly** [comment]
Meeting January 18, 2020: decision to keep version attribute as is (optional). Version information is seen as...WP4_r3455    WP\d{1,9}(\_r\d+)?$
.
