### ISSUE TITLE
"type" attribute for GraphicalLines and Interactions

### ISSUE THREAD

**Issue by ariutta** [PathVisio/GPML#20]
Is the "type" attribute being used anywhere for Interactions and GraphicalLines?

It is specified in both GPML2013a and in GPML2017, but I can't figure out any way to actually set a type value for these elements in PathVisio.

If it's not being used anywhere, should it be deleted from GPML2017?

type attribute for GraphicaLine in GPML2017:
https://github.com/PathVisio/GPML/blob/df4209fa5f7d07e2a9ec0d245cb3a665b832b5fe/GPML2017.xsd#L433

for Interaction:
https://github.com/PathVisio/GPML/blob/df4209fa5f7d07e2a9ec0d245cb3a665b832b5fe/GPML2017.xsd#L492

**Comment by AlexanderPico** [comment]
Indeed. I can't see any UI in PathVisio to set "type". It is distinct from "connectorType". Maybe we had some dream usage in mind originally or it's vestigial from GenMAPP days...

I'd also vote to ditch it in 2017a

**Comment by saurabhkumar13** [comment]
True, I am not sure about the usage but I think the attribute is ignored by the XML reader in libGPML/PathVisio

**Comment by saurabhkumar13** [comment]
removed from the schema

**Comment by Finterly** [comment]
Implemented in GPML 2021 Schema. commit 0135cac closes issue #20.

Interaction.type and GraphicalLine.type removed.
