### ISSUE TITLE
Editor defaults from XSD (e.g., fontSize for elements like DataNodes)

### ISSUE THREAD

**Issue by ariutta** [PathVisio/GPML#21]
Sometime ago, we decided to use the XSD file to keep the editors for PathVisio and pvjs in sync for things like default values. I'm trying to think of how this would work.

For example, the default `fontSize` for a DataNode is "12" as per the current GPML2017:
https://github.com/PathVisio/GPML/blob/df4209fa5f7d07e2a9ec0d245cb3a665b832b5fe/GPML2017.xsd#L48

But if you make a DataNode in PathVisio, the font size that PathVisio sets for all DataNode types is "10", except for type Pathway, which is "12". So there would be a difference between the two editors if pvjs follows the XSD and make all DataNodes with a font size of "12".

Do we need another file to set defaults for things like DataNode by Type and Group by Style?

**Comment by AlexanderPico** [comment]
I don't have an opinion on this. If you have a solution in mind, go ahead and implement it and share it with the group.

**Comment by ariutta** [comment]
Some of these defaults are currently only located in the Java code, so maybe @mkutmon has a good suggestion for what to do here.

**Comment by mkutmon** [comment]
All defaults should be in the XSD and all viewers and editors should get them from the XSD. It might be that some defaults are not yet read out by PathVisio but that will be updated after libGPML is integrated.

**Comment by mkutmon** [comment]
I actually think that I fixed the 12 textsize issue and new datanodes should have textsize 12 but I'll check again

**Comment by mkutmon** [comment]
@saurabhkumar13 can we check all default values again and add default values if appropriate (e.g. GroupType, DataNode type, etc).

**Comment by saurabhkumar13** [comment]
I think if any default values are missing it should be possible to fill those while reading them.
But in the case PathVisio sets different values from the default, it would be difficult to figure out if that value was meant to be there or not, just by reading the gpml.

**Comment by ariutta** [comment]
Will some of these defaults be specified in the Java code but not the XSD? Two more examples where the outputs would differ when using PathVisio vs. the XSD defaults:

|Class           | Type          | Property | PathVisio | GPML2017
|------------|------------|----------|----------|-----------
| DataNode  | any             | vAlign      | Middle     | Top
| DataNode  | Metabolite | color       | 0000ff    | Black

**Comment by mkutmon** [comment]
Hmm I would like to define all defaults in the XSD and not in Java. Although the two examples that you provide show that this will be tricky. Since we can only define one default color for DataNode, we won't be able to define the blue for metabolite, I guess. Do you have any ideas how we could do this - or do we need a separate config file for that?

**Comment by ariutta** [comment]
Setting the default value for `vAlign` for `DataNode` would be pretty easy in the XSD. We'd either change `FontAttributes` to have a default `vAlign` of "`Middle`" [here](
https://github.com/PathVisio/GPML/blob/df4209fa5f7d07e2a9ec0d245cb3a665b832b5fe/GPML2017.xsd#L59), or we'd create a `VAlignType`, specify a default of "`Top`" in `FontAttributes` and add an override to the `DataNode` class like this:
```xml
<xsd:attribute name="vAlign" type="gpml:VAlignType" default="Middle"/>
```

For setting Metabolite to be blue, that's trickier, and I don't know of an easy solution. We could create separate classes for each `DataNode` type, e.g., `DataNodeMetabolite`, and then specify defaults per type. But that sounds complicated, and I really don't want to make things any more complicated than they need to be.

**Comment by Finterly** [comment]
vAlign default "Middle"
textSize default "12" 

Defaults will be enforced in libPathVisio.
