### ISSUE TITLE
BioPAX

### ISSUE THREAD

**Issue by ariutta** [PathVisio/GPML#3]
* [ ] should we continue using BioPAX3 inside GPML?
* [ ] if so, we need to fix several errors in our BioPAX inside our GPML:

Here's some JS code that fixes the errors:
``` js
    // Fix errors with how GPML currently represents BioPAX
    // biopaxString is the stringified version of the BioPAX element and all its descendants
   biopaxString.replace(/bp:ID/g, 'bp:id')
      .replace(/bp:DB/g, 'bp:db')
      .replace(/bp:TITLE/g, 'bp:title')
      .replace(/bp:SOURCE/g, 'bp:source')
      .replace(/bp:YEAR/g, 'bp:year')
      .replace(/bp:AUTHORS/g, 'bp:author')
      .replace(/rdf:id/g, 'rdf:ID')
      .replace(/Biopax xmlns="http:\/\/pathvisio.org\/GPML\/2013a"/,
      'Biopax xmlns="http://pathvisio.org/GPML/2013a" ' +
          'xmlns:xsd="http://www.w3.org/2001/XMLSchema#" ' +
          'xmlns:owl="http://www.w3.org/2002/07/owl#" ' +
          'xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" ' +
          'xmlns:bp="http://www.biopax.org/release/biopax-level3.owl#"');
```

**Comment by ariutta** [comment]
We may also be using `rdf:id` where we should be using `rdf:about` in some places.

**Comment by mkutmon** [comment]
I would actually prefer to clean this part up and remove the BioPAX from within the GPML. These issues should be solved in the BioPAX converters.

**Comment by egonw** [comment]
@mkutmon what would you suggest? To just list the PubMed ID in the GPML? Or use perhaps BIBO in XML format, or?

**Comment by mkutmon** [comment]
@egonw yes, more like BIBO in XML and definitely more than just the pubmed id. it should be more generic - not pubmed focussed (although changes in WP and PV need to follow to display and add not pubmed refs) - and BIBO is probably a good start to look at.

**Comment by mkutmon** [comment]
Decision June 19: 
Citations - Citation → citationId / CitationRef

**Comment by ariutta** [comment]
~~Does that sound right? If we're using properties like `graphRef` and `groupRef`, wouldn't `citationRef` be a property and start with a lowercase "c"?~~

**Comment by ariutta** [comment]
Edited: I remember now -- my example below doesn't work, because we can have multiple CitationRefs per DataNode.

~~So we could have something like this:~~

```
<DataNode ID="m24h" citationRef="s6ua">
  ...
</DataNode>
<Citation ID="s6ua">
  ...
</Citation>
```

**Comment by mkutmon** [comment]
Yes exactly. So CitationRef and OntologyTagRef need to be elements.

**Comment by mkutmon** [comment]
Solved in GPML2017
