### ISSUE TITLE
Why both GraphId and GroupId?

### ISSUE THREAD

**Issue by ariutta** [PathVisio/GPML#4]
Is there a reason that we have both? It would be simpler to just use `GraphId`. To express that an element is in a group, it would have the attribute `GroupRef="abc123"` where "abc123" is the `GraphId` of a Group.

**Comment by ariutta** [comment]
We would still have both `GroupRef` and `GraphRef`. The only difference is that they would always refer to  `GraphId` values for other elements.

**Comment by mkutmon** [comment]
June 19 call: remove groupId --> use Group's graphId when references with groupRef

**Comment by mkutmon** [comment]
solved in GPML2017

**Comment by Finterly** [comment]
For GPML 2021 Schema - Group's GroupId and GraphId are merged as elementId. GroupRef of pathway elements will be elementRef. This is possible because no pathway element has both GroupRef and GraphRef.
