### ISSUE TITLE
Anchor Shape

### ISSUE THREAD

**Issue by ariutta** [PathVisio/GPML#6]
If you look at the GPML at the bottom of this issue, you'll see both of these attributes:
* `ShapeType="Oval"`
* `Shape="Circle"`

1) `Shape` vs. `ShapeType`: should we be consistent and use `ShapeType` for all?
2) A perfectly circular Anchor uses `Circle` whereas a perfectly circular node of another type uses `Oval`: should these be consistent? If we make a change, it's interesting to note that most other graphics libraries appear to use `Ellipse` instead of `Oval`

```xml
  <DataNode TextLabel="GeneProduct" GraphId="d0c9e" Type="GeneProduct">
    <Graphics CenterX="290.0" CenterY="417.0" Width="80.0" Height="80.0" ZOrder="32768" FontSize="10" Valign="Middle" ShapeType="Oval" />
    <Xref Database="" ID="" />
  </DataNode>
  <Interaction>
    <Graphics ZOrder="12288" LineThickness="1.0">
      <Point X="374.0" Y="168.0" />
      <Point X="584.0" Y="462.0" ArrowHead="Arrow" />
      <Anchor Position="0.4" Shape="Circle" />
    </Graphics>
    <Xref Database="" ID="" />
  </Interaction>
```

**Comment by saurabhkumar13** [comment]
renamed Anchor@shape to Anchor@shapeType
