### ISSUE TITLE
GPML vs. BridgeDb Vocab

### ISSUE THREAD

**Issue by ariutta** [PathVisio/GPML#7]
There are some discrepancies between the BridgeDb vocab and GPML. For example, we have:

* [gpml:database](https://vocabularies.wikipathways.org/gpml#database)
* [bdb:hasDataSource](http://vocabularies.bridgedb.org/ops#hasDataSource)
* [gpml:data-Source](https://vocabularies.wikipathways.org/gpml#data-Source)
* [bdb:DataSource](http://vocabularies.bridgedb.org/ops#DataSource)

Our community generally uses the term "data source" as in `bdb:DataSource`, but in GPML, we use the term "database," as in `gpml:database`, which appears to correspond to `bdb:hasDataSource`. `gpml:data-Source/Data-Source` appears to be an unused attribute for the Pathway element: 

`<Pathway xmlns="http://pathvisio.org/GPML/2013a" Name="WikiPathways Academy: met-1-indirect" Data-Source="example">`

Is that referring to the concept described by [void:Dataset](http://vocab.deri.ie/void#Dataset) and [schema:Dataset](https://schema.org/Dataset)? Should we get rid of it?

**Comment by Finterly** [comment]
GPML 2021 uses the term dataSource
