### ISSUE TITLE
GPML vs. GPML Vocab

### ISSUE THREAD

**Issue by ariutta** [PathVisio/GPML#8]
There are some discrepancies between the [GPML Vocabulary](https://vocabularies.wikipathways.org/gpml) and GPML, such as:

* [ ] Capitalization of attribute names, e.g., [gpml:data-Source](https://vocabularies.wikipathways.org/gpml#data-Source) vs. `Data-Source="example"` or [gpml:zorder](https://vocabularies.wikipathways.org/gpml#zorder) vs. `ZOrder=3`. Proposal: change GPML attribute names to use lowercase for the first letter in order to make GPML consistent with the vocab and with RDF conventions (property names start with lowercase and class names start with uppercase). HTML also uses lowercase attribute names.
* [ ] What is the difference between [gpml:hasGroup](https://vocabularies.wikipathways.org/gpml#hasGroup) and [gpml:groupRef](https://vocabularies.wikipathways.org/gpml#groupRef)? Are they synonyms? If so, can we pick just one to use?
* [ ] [gpml:fontStyle](https://vocabularies.wikipathways.org/gpml#fontStyle) vs. [gpml:fontName](https://vocabularies.wikipathways.org/gpml#fontName) vs. `FontStyle="Italic"` vs. `FontName="Helvetica"`: the definition for fontStyle in the vocab doesn't match the GPML usage, because in GPML, we never say `FontStyle="Helvetica"`

**Comment by ariutta** [comment]
@egonw, what do you think about the difference between `zorder` in our GPML Vocab vs. `ZOrder` in our GPML XML? Earlier, we've said the GPML Vocab should describe the GPML XML, so should we make the attribute names in GPML XML use lowerCamelCase for GPML2017a?

**Comment by Finterly** [comment]
This issue has since been resolved.
