### ISSUE TITLE
Purpose of Graphics Element

### ISSUE THREAD

**Issue by ariutta** [PathVisio/GPML#9]
What benefit do we get from having a Graphics element? We could reduce filesize and simplify by just moving the attributes from the Graphics element to the parent, e.g.:

```xml
  <DataNode TextLabel="GeneProduct"
      GraphId="d0c9e"
      Type="GeneProduct">
    <Graphics CenterX="290.0"
      CenterY="417.0"
      Width="80.0"
      Height="80.0" />
    <Xref Database="" ID="" />
  </DataNode>
```

to

```xml
  <DataNode TextLabel="GeneProduct"
      GraphId="d0c9e"
      Type="GeneProduct"
      CenterX="290.0"
      CenterY="417.0"
      Width="80.0"
      Height="80.0">
    <Xref Database="" ID="" />
  </DataNode>
```

**Comment by ariutta** [comment]
@mkutmon Replying to [your comment](https://github.com/PathVisio/GPML/issues/2#issuecomment-308971185) about the `Graphics` element here...

For my work, simpler is generally easier! :) As [Google's JSON styleguide](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Flattened_data_vs_Structured_Hierarchy#Flattened_data_vs_Structured_Hierarchy) says:
># Flattened data vs Structured Hierarchy
> Data should not be arbitrarily grouped for convenience.

So if there's a good reason for different groupings, that's fine, but otherwise, it sounds great to  keep the data flat.

**Comment by Finterly** [comment]
At meeting January 18, 2020:  was decided to maintain Graphics element.
